### ISSUE TITLE
请问left.html 里getQueryString('to')||'marker' 何用？

### ISSUE THREAD

**Issue by raystin** [liusaint/baiduMap#1]
如题，

**Comment by liusaint** [comment]
getQueryString('to')这个函数是用来获取url地址中的参数的。  这句话代码意思是如果没获取到参数那就默认值为‘marker'。  JavaScript的短路操作。  ||前面的有值，就不会执行||后面的。  http://runningls.com/demos/baidumap/index.html?to=marker  你打开看看，我在地地址上写一个对应的参数，iframe右边就可以跳转到对应的页面去。   算是个附加功能。不过当时没考虑如果to后面参数写错的情况。

**Comment by raystin** [comment]
谢谢，答复！！我也是在看的时候，觉得奇怪，这段在目前的例子中没什么作用
